name: Publish
on: [workflow_dispatch]

jobs:
    build:
      name: Publish
      runs-on: ubuntu-latest
      steps:
      - name: Check out repo
        uses: actions/checkout@v1
      - name: Publish
        env:
          APIKEY: ${{ secrets.APIKEY }}
        run: .\publish.ps1
        shell: pwsh